<!DOCTYPE HTML>

<html lang="en">
	<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />

	<title>[@title]</title>
	<meta name="description" content="[@title]">
	<meta name="author" content="Graham Ogden">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script>
	<link rel="stylesheet" href="/css/main.css?[@css-time]">
	<!--[if lt IE 9]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body>
	<div id="body_wrapper">
		<div id="body_container">
			<h2>4 (D')Oh 4</h2>
			<p>Sorry, you have not specified a JavaScript Game Engine Library that you wish to use.</p>
		</div>
	</div>
</body>
</html>